services:
  server:
    image: node:20-alpine
    working_dir: /home/node/lego-server
    command: sh -c "yarn install && yarn start"
    restart: unless-stopped
    ports:
      - 3010:3010
    volumes:
      - "./server/:/home/node/lego-server"
