name: Server

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build server container with tag version
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set variables
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.LEGO_SERVER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.LEGO_SERVER_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_CONTAINER_REGISTRY_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: lego-server
        TAG: ${{ steps.vars.outputs.tag }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$TAG .
        docker push $REGISTRY/$REPOSITORY:$TAG
